#!/bin/sh

# PROVIDE: fatcoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# fatcoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable fatcoin service.
# fatcoin_config (path): Set to /usr/local/etc/fatcoin.conf by default.
# fatcoin_user:  The user account fatcoin daemon runs as. It uses 'root' user by default.
# fatcoin_group: The group account fatcoin daemon runs as. It uses 'wheel' group by default.
# fatcoin_datadir (str): Default to "/var/db/fatcoin". Base data directory.

. /etc/rc.subr

name=fatcoin
rcvar=fatcoin_enable

: ${fatcoin_enable:=NO}
: ${fatcoin_config=/usr/local/etc/fatcoin.conf}
: ${fatcoin_datadir=/var/db/fatcoin}
: ${fatcoin_user="root"}
: ${fatcoin_group="wheel"}

required_files=${fatcoin_config}
command=/usr/local/bin/fatcoind
fatcoin_chdir=${fatcoin_datadir}
pidfile="${fatcoin_datadir}/fatcoind.pid"
stop_cmd=fatcoin_stop
command_args="-conf=${fatcoin_config} -datadir=${fatcoin_datadir} -noupnp -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

fatcoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${fatcoin_datadir}
	[ $? -eq 0 ] && chown -R ${fatcoin_user}:${fatcoin_group} ${fatcoin_datadir}
}

fatcoin_prestart()
{
	if [ ! -d "${fatcoin_datadir}/." ]; then
		fatcoin_create_datadir || return 1
	fi
}

fatcoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

fatcoin_stop()
{
    fatcoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${fatcoin_config} -datadir=${fatcoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
